version: "3.8"

services:
  app:
    container_name: nodetify-dev
    restart: always
    image: nodetify-dev
    build:
      context: ../app
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
      - 4321:4321
    env_file:
      - ./env/app.env
    volumes:
      - "../app:/app"
    networks:
      - nodetify-network
    depends_on:
      - db
    command: "npm run dev"
  db:
    image: postgres:15
    container_name: db-nodetify-dev
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nodetify-network
volumes:
  db_data:
    driver: local
networks:
  nodetify-network:
    driver: bridge