version: "3.8"

services:
  app:
    container_name: nodetify-prod
    restart: always
    image: nodetify-prod
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    command: "npm start"