version: "3.8"

services:
  app:
    container_name: nodetify-prod
    restart: always
    image: nodetify-prod
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    environment:
      - NODE_ENV=production
      - PORT=4321
    command: "npm start"